language: python
python:
  - '3.6'
before install:
  - python setup.py install
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - cd climops/tests/
  - python -m unittest discover
after_success:
  - coveralls
