sudo: false

language: python

python:
  - '3.6'
  
install:
  - pip install -r requirements.txt
  - pip install .
  - pip install codecov
  - pip install coverage
script:
  - cd climops/
  - python -m unittest discover
  - coverage run tests.py
after_success:
  - codecov --token=b28bbcca-05f1-41e3-8b8d-6ee27690bad7
